aeroplanes/urls.py
from django.conf.urls import url, include
from . import views
from log import urls as techlog_urls
__author__ = 'Lee.Gent'

urlpatterns = [
    url(r'^(?P<aeroplane_reg>[\w\d-]+)/$', views.aeroplane, name="aeroplane"),
    url(r'^(?P<aeroplane_reg>[\w\d-]+)/xml/v1$', views.aeroplane_xml_v1, name="aeroplane_xml"),
    url(r'^(?P<aeroplane_reg>[\w\d-]+)/consumables$', views.consumables, name="consumables"),
    url(r'^(?P<aeroplane_reg>[\w\d-]+)/log/', include(techlog_urls)),
]

log/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views
__author__ = 'Lee.Gent'

urlpatterns = [
    url(r'^$', views.log_entries_redirect, name='techlogentrylist'),
    url(r'^(?P<year>\d+)/(?P<month>\d+)$', views.log_entries, name="techlogentrylist_by_date"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/technical$', views.log_entries_technical, name="techlogentrylist_technical"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/technical/print$', views.log_entries_technical_print, name="techlogentrylist_technical_print"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/xml$', views.log_entries_xml, name="techlogentrylist_by_date_xml"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/xml/v1.0$', views.log_entries_xml, name="techlogentrylist_by_date_xml"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/xml/v0.1$', views.log_entries_xml_v01, name="techlogentrylist_by_date_xml"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/json$', views.log_entries_json, name="techlogentrylist_by_date_json"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/monthsummary$', views.month_summary, name="log_month_summary"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/cap398$', views.cap398, name="cap398_by_date"),
    url(r'^(?P<year>\d+)/(?P<month>\d+)/cap398/print$', views.cap398_print, name="cap398_by_date_print"),
    url(r'^add$', views.add_flight, name='addflight'),
    url(r'^(?P<pk>\d+)/$', views.view_entry, name="logentry"),
    url(r'^delete/(?P<pk>\d+)/$', views.delete_logentry, name="delete_logentry"),
    url(r'^members/$', views.group_member_list, name="group_member_list"),
    url(r'^members/(?P<member_id>\d+)/statement/$', views.group_member_statement, name="group_member_statement"),
    url(r'^members/(?P<member_id>\d+)/statement/export/$', views.group_member_statement_export, name="group_statement_export"),
    url(r'^dump-weeks/(?P<weeks>\d+)/$', views.dump_last_x_weeks, name="dump_weeks"),
]

techlog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from dashboard import views
from group import urls as group_urls
from aeroplanes import urls as aeroplanes_urls
from registration import urls as registration_urls

urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^registration/', include(registration_urls)),
    url(r'^dashboard', views.dashboard),
    url(r'^groups/', include(group_urls)),
    url(r'^aeroplanes/', include(aeroplanes_urls)),
    url(r'^admin/', include(admin.site.urls)),
]

aeroplanes/models.py
from __future__ import unicode_literals
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta
from django.db import models
from django.conf import settings
from django.contrib.auth.models import Group
from django.db.models import Sum, F, Value
from django.utils import timezone


class CalendarCheck(object):
    def __init__(self, check_type, check_before):
        self.check_type = check_type
        self.check_before = check_before


class FlyingHoursCheck(object):
    def __init__(self, check_type, check_in_flying_hours, check_at_flying_hours):
        self.check_type = check_type
        self.check_in_flying_hours = check_in_flying_hours
        self.check_at_total_flying_hours = check_at_flying_hours


class CheckPair(object):
    def __init__(self, flying_hours_check, calendar_check):
        self.flying_hours_check = flying_hours_check
        self.calendar_check = calendar_check


SECS_IN_HOUR=60*60
def decimalise_timedelta(timedelta):
    seconds = timedelta.total_seconds()
    return seconds / SECS_IN_HOUR


class Aeroplane(models.Model):
    MAX_HOURS_BETWEEN_CHECKS = 50
    MAX_MONTHS_BETWEEN_CHECKS = 6

    CHECK_TYPE_50_HOURS_1 = "50HOURS1"
    CHECK_TYPE_50_HOURS_2 = "50HOURS2"
    CHECK_TYPE_150_HOURS = "150HOURS"
    CHECK_TYPE_ANNUAL = "ANNUAL"

    NEXT_CHECK_MAP = {
            CHECK_TYPE_50_HOURS_1: CHECK_TYPE_50_HOURS_2,
            CHECK_TYPE_50_HOURS_2: CHECK_TYPE_150_HOURS,
            CHECK_TYPE_150_HOURS: CHECK_TYPE_50_HOURS_1,
            CHECK_TYPE_ANNUAL: CHECK_TYPE_50_HOURS_1
    }

    CHECK_TYPE_CHOICES = (
        (CHECK_TYPE_50_HOURS_1, "50 hours (first)"),
        (CHECK_TYPE_50_HOURS_2, "50 hours (second)"),
        (CHECK_TYPE_150_HOURS, "150 hours"),
        (CHECK_TYPE_ANNUAL, "Annual"),
    )

    owning_group = models.ForeignKey(Group)

    registration = models.CharField(max_length=10)
    registered = models.DateField()

    manufacturer = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    model = models.CharField(max_length=200)
    mtow = models.IntegerField()
    built = models.IntegerField()

    engine_count = models.IntegerField()
    engine = models.CharField(max_length=100)
    propeller = models.CharField(max_length=100)

    last_annual = models.DateTimeField()

    opening_tte = models.FloatField()  # hours and hundredths of hours
    opening_time = models.FloatField()
    opening_ttp = models.FloatField()

    arc_expiry = models.DateField()
    insurance_expiry = models.DateField()
    radio_expiry = models.DateField()

    def __str__(self):
        return "{0} ({1})".format(self.registration, self.model)

    def _generate_initial_check(self):
        c = Check()
        c.aeroplane = self
        c.time = self.last_annual
        c.type = self.CHECK_TYPE_ANNUAL
        c.ttaf = self.opening_time
        c.tte = self.opening_tte
        c.ttp = self.opening_ttp
        return c

    def get_last_check(self):
        last_check = self.check_set.order_by("time").last()
        if last_check is not None:
            return last_check
        # Oh! New 'plane?
        return self._generate_initial_check()

    def get_last_check_from(self, fromdate):
        last_check = self.check_set.filter(time__lte=fromdate).order_by("time").last()
        if last_check is not None:
            return last_check
        # Oh! New 'plane?
        return self._generate_initial_check()

    def _airborne_time_since_check(self, check):
        logged_dict = self.techlogentry_set.filter(departure_time__gt=check.time).annotate(db_block_time=(F('arrival_time') - F('departure_time'))).annotate(db_airborne_time=F('db_block_time')-Value("PT10M")).aggregate(total_logged_airborne=Sum('db_airborne_time'))
        logged = logged_dict["total_logged_airborne"]
        if logged is None:
            logged = 0
        else:
            logged = decimalise_timedelta(logged)

        return logged


    @property
    def ttaf(self):
        # Current TTAF is the TTAF at the last check [or opening number] + how many AF hours since
        last_check = self.get_last_check()
        logged = self._airborne_time_since_check(last_check)
        return last_check.ttaf + logged

    @property
    def tte(self):
        # Current TTE is the TTE at the last check [or opening number] + how many flight hours since
        last_check = self.get_last_check()
        logged = self._airborne_time_since_check(last_check)
        return last_check.tte + logged

    @property
    def ttp(self):
        # Current TTP is the TTP at the last check [or opening number] + how many flight hours since
        last_check = self.get_last_check()
        logged = self._airborne_time_since_check(last_check)
        return last_check.ttp + logged

    @property
    def flown_hours_since_check(self):
        #  Sum of tech log entries
        # TODO: remove circular dependency :-/

        # Total hours minus last check hours (if any)
        # Where total is all in logbook + opening total
        last_check = self.get_last_check()

        ttaf = self.ttaf

        flown_since_last_check = ttaf - last_check.ttaf

        return flown_since_last_check

    @property
    def next_flying_hours_check(self):
        last = self.get_last_check()
        next_flying_hours_check = self.calc_next_flying_hours_check(last.type, last.ttaf, self.flown_hours_since_check)
        return next_flying_hours_check

    @property
    def next_check_pair(self):
        last = self.get_last_check()
        check_pair = self.calc_next_check_pair(last.time, self.last_annual, last.type, last.ttaf, self.flown_hours_since_check)
        return check_pair

    @classmethod
    def calc_next_flying_hours_check(cls, last_check_type, last_check_ttaf, flown_hours):
        next_check_type = cls.NEXT_CHECK_MAP[last_check_type]
        next_check_in_flying_hours = cls.MAX_HOURS_BETWEEN_CHECKS - flown_hours
        next_check_at_ttaf_hours = cls.MAX_HOURS_BETWEEN_CHECKS + last_check_ttaf

        return FlyingHoursCheck(next_check_type, next_check_in_flying_hours, next_check_at_ttaf_hours)

    @classmethod
    def calc_next_calendar_check(cls, last_check_at, last_annual_check_at):
        next_annual_at = last_annual_check_at + relativedelta(years=+1)
        next_50hrs_at = last_check_at + relativedelta(months=+cls.MAX_MONTHS_BETWEEN_CHECKS)

        next_check_before, next_calendar_check_is = ((next_annual_at, Aeroplane.CHECK_TYPE_ANNUAL) if next_annual_at <= next_50hrs_at else (next_50hrs_at, Aeroplane.CHECK_TYPE_50_HOURS_1))

        return CalendarCheck(next_calendar_check_is, next_check_before)

    @classmethod
    def calc_next_check_pair(cls, last_check_at, last_annual_check_at, last_check_type, last_check_ttaf, flown_hours):
        next_flying_hours_check = cls.calc_next_flying_hours_check(last_check_type, last_check_ttaf, flown_hours)
        next_calendar_check = cls.calc_next_calendar_check(last_check_at, last_annual_check_at)

        return CheckPair(next_flying_hours_check, next_calendar_check)


class Check(models.Model):
    aeroplane = models.ForeignKey(Aeroplane)
    time = models.DateTimeField()
    type = models.CharField(max_length=10, choices=Aeroplane.CHECK_TYPE_CHOICES)
    ttaf = models.FloatField()
    tte = models.FloatField(default=0)
    ttp = models.FloatField(default=0)

    def __str__(self):
        return "{0} check for {1} on {2} @ {3} TTAF".format(self.type, self.aeroplane, self.time, self.ttaf)

aeroplanes/forms.py
from django.forms import ModelForm
from .models import Aeroplane

__author__ = 'Lee.Gent'

class AeroplaneForm(ModelForm):
    class Meta:
        model = Aeroplane
        fields =\
            [
                'owning_group',
                'registration',
                'registered',
                'manufacturer',
                'type',
                'model',
                'mtow',
                'built',
                'engine_count',
                'engine',
                'propeller',
                'last_annual',
                'opening_tte',
                'arc_expiry',
                'radio_expiry',
                'insurance_expiry'
            ]

aeroplanes/views.py
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponseRedirect, HttpResponseForbidden, HttpResponse
from log.models import TechLogEntry
from log.views import ConsumablesSummary
from .models import Aeroplane
from .forms import AeroplaneForm
from io import StringIO


@login_required
def aeroplane(request, aeroplane_reg):
    ac = get_object_or_404(Aeroplane, registration=aeroplane_reg)
    form = AeroplaneForm(instance=ac)
    return render(request, "aeroplanes/aeroplane.html", {"aeroplane": ac, "last_check": ac.get_last_check(),
                                                         "form": form})


def aeroplane_xml_v1(request, aeroplane_reg):
    ac = get_object_or_404(Aeroplane, registration=aeroplane_reg)
    stream = StringIO()
    
    stream.write("<?xml version='1.0' encoding='UTF-8' ?>")
    stream.write("<aeroplane regstration='{}'>".format(ac.registration))
    stream.write("<ttaf>{}</ttaf>".format(ac.ttaf))
    stream.write("<tte>{}</tte>".format(ac.tte))
    stream.write("<ttp>{}</ttp>".format(ac.ttp))
    stream.write("</aeroplane>")

    payload = stream.getvalue()
    stream.close()
    return HttpResponse(payload, content_type="text/xml")


def _populate_consumables_usage_within_last(days, aeroplane):
    now = timezone.now()
    days_ago_x = now - timezone.timedelta(days=days)
    flights_in_x = TechLogEntry.objects.filter(aeroplane=aeroplane, departure_time__gt=days_ago_x)

    consumables_in_x = ConsumablesSummary()
    for flight in flights_in_x:
        consumables_in_x.airborne += flight.airborne_time
        consumables_in_x.fuel += flight.fuel_uplift
        consumables_in_x.oil += flight.oil_uplift
    return consumables_in_x


def _populate_total_consumables_usage(aeroplane):
    flights_in_x = TechLogEntry.objects.filter(aeroplane=aeroplane)

    consumables_in_x = ConsumablesSummary()
    for flight in flights_in_x:
        consumables_in_x.airborne += flight.airborne_time
        consumables_in_x.fuel += flight.fuel_uplift
        consumables_in_x.oil += flight.oil_uplift
    return consumables_in_x

@login_required
def consumables(request, aeroplane_reg):
    ac = get_object_or_404(Aeroplane, registration=aeroplane_reg)
    first_flight = TechLogEntry.objects.filter(aeroplane=ac).order_by('departure_time').first()
    now = timezone.now()
    diff = now - first_flight.departure_time

    consumables_usage_map = {
        diff.days: _populate_total_consumables_usage(ac),
        30: _populate_consumables_usage_within_last(30, ac),
        60: _populate_consumables_usage_within_last(60, ac),
        90: _populate_consumables_usage_within_last(90, ac),
        120: _populate_consumables_usage_within_last(120, ac),
    }

    return render(request, "aeroplanes/consumables.html", {"aeroplane": ac, "consumables": consumables_usage_map})

aeroplanes/templates/aeroplanes/aeroplane.html
{% extends "global/root.html" %}
{% load decimaltime %}

{% load staticfiles %}

{% block content %}
        <div class="panel panel-default">
            <div class="panel-heading">Aeroplane Details</div>
            <table class="table table-responsive">
                <tr class="info">
                    <td colspan="2">
                        Registration
                    </td>
                </tr>
                <tr>
                    <th>Registration</th>
                    <td>{{ aeroplane.registration }}</td>
                </tr>
                <tr>
                    <th>Owning Group</th>
                    <td><a href="{% url 'group' aeroplane.owning_group.id %}">{{ aeroplane.owning_group.name }}</a></td>
                </tr>
                <tr>
                    <th>Registered</th>
                    <td>{{ aeroplane.registered }}</td>
                </tr>

                <tr class="info">
                    <td colspan="2">
                        Technical
                    </td>
                </tr>

                <tr>
                    <th>Manufacturer</th>
                    <td>{{ aeroplane.manufacturer }}</td>
                </tr>
                <tr>
                    <th>Type</th>
                    <td>{{ aeroplane.type }}</td>
                </tr>
                <tr>
                    <th>Model</th>
                    <td>{{ aeroplane.model }}</td>
                </tr>
                <tr>
                    <th>MTOW</th>
                    <td>{{ aeroplane.mtow }} kg</td>
                </tr>
                <tr>
                    <th>Engines</th>
                    <td>{{ aeroplane.engine_count }}</td>
                </tr>
                <tr>
                    <th>Engine</th>
                    <td>{{ aeroplane.engine }}</td>
                </tr>
                <tr>
                    <th>Propeller</th>
                    <td>{{ aeroplane.propeller }}</td>
                </tr>

                <tr class="info">
                    <td colspan="2">
                        Maintenance
                    </td>
                </tr>

                <tr>
                    <th>Total Time Airframe</th>
                    <td>{{ aeroplane.ttaf|humanise_longhours }}</td>
                </tr>

                <tr>
                    <th>Total Time Engine</th>
                    <td>{{ aeroplane.tte|humanise_longhours }}</td>
                </tr>

                <tr>
                    <th>Total Time Propeller</th>
                    <td>{{ aeroplane.ttp|humanise_longhours }}</td>
                </tr>

                <tr>
                    <th>Last Check</th>
                    <td>{{ last_check.time }}</td>
                </tr>

                <tr>
                    <th>Last Check Type</th>
                    <td>{{ last_check.get_type_display }}</td>
                </tr>
                <tr>
                    <th>Last Check TTAF</th>
                    <td>{{ last_check.ttaf|humanise_longhours }}</td>
                </tr>
                <tr>
                    <th>Last Annual Check</th>
                    <td>{{ aeroplane.last_annual }}</td>
                </tr>
                <tr>
                    <th>ARC Expiry</th>
                    <td>{{ aeroplane.arc_expiry }}</td>
                </tr>

                <tr>
                    <th>Radio License Expiry</th>
                    <td>{{ aeroplane.radio_expiry }}</td>
                </tr>

                <tr>
                    <th>Insurance Expiry</th>
                    <td>{{ aeroplane.insurance_expiry }}</td>
                </tr>
            </table>
        </div>
{% endblock %}

aeroplanes/templates/aeroplanes/consumables.html
{% extends "global/root.html" %}
{% load decimaltime %}

{% load staticfiles %}

{% block content %}
        <div class="panel panel-default">
            <div class="panel-heading">Consumables Summary</div>
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <th>Period</th>
                        <th>Airborne Hours (hh:mm)</th>
                        <th>Fuel Used (L)</th>
                        <th>Oil Used (L)</th>
                        <th>Fuel Consumption (L/a.b. hours)</th>
                        <th>Oil Consumption (L/a.b. hours)</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for period, consumables_summary in consumables.items %}
                    <tr>
                    <td>Last {{ period }} days</td>
                    <td>{{ consumables_summary.airborne }}</td>
                    <td>{{ consumables_summary.fuel }}</td>
                    <td>{{ consumables_summary.oil }}</td>
                    <td>{{ consumables_summary.fuel_litres_per_hour|floatformat:2 }}</td>
                    <td>{{ consumables_summary.oil_litres_per_hour|floatformat:2 }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
            </table>
        </div>

{% endblock %}